INSERT INTO Customer (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH) VALUES (1, 'Jowsh', 'Badymoon', TO_DATE('17/12/2015', 'DD/MM/YYYY'));
INSERT INTO Customer (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH) VALUES (2, 'Jawsh', 'Badymoon', TO_DATE('17/12/2015', 'DD/MM/YYYY'));
