INSERT INTO Account (ACCOUNT_ID, ACCOUNT_NO, BSB, PRODUCT_NAME) VALUES (1, '12344321', '062181', 'Max Save');
INSERT INTO Customer (CUSTOMER_ID, FIRST_NAME, LAST_NAME) VALUES (1, 'Jowsh', 'Badymoon');
INSERT INTO Customer (CUSTOMER_ID, FIRST_NAME, LAST_NAME) VALUES (2, 'Jawsh', 'Badymoon');
INSERT INTO OWNED_BY (CUSTOMER_ID, ACCOUNT_ID) VALUES (1,1);
INSERT INTO OWNED_BY (CUSTOMER_ID, ACCOUNT_ID) VALUES (2,1);
